/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <system_stm32f4xx.h>
#include <timer.h>
#include <Ucglib.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
static ucg_t ucg;


int main(void)
{
	SystemCoreClockUpdate();
	TimerInit();

	// khoi tao LCD
	Ucglib4WireSWSPI_begin(&ucg, ucg_font_ncenR24_tf);
	ucg_ClearScreen(&ucg);

	ucg_SetFont(&ucg, ucg_font_helvR08_tf);
	ucg_SetColor(&ucg, 0, 255, 255, 255);
	ucg_SetColor(&ucg, 1, 0, 0, 0);

	ucg_SetRotate180(&ucg);
	ucg_DrawString(&ucg, 24, 12, 0,"I love PTIT");	// 10: cot; 12: hang
	ucg_DrawString(&ucg, 24, 26, 0, "so much");
    /* Loop forever */
		while(1){
			processTimerScheduler();
		}
}
